/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/animals": {
    get: {
      parameters: {
        query: {
          type?: components["schemas"]["AnimalType"];
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": (
              | components["schemas"]["Dog"]
              | components["schemas"]["Cat"]
            )[];
          };
        };
      };
    };
  };
}

export interface components {
  schemas: {
    /** @enum {string} */
    AnimalType: "All" | "Cats" | "Dogs";
    /** @description Base animal type. */
    Animal: {
      type: components["schemas"]["AnimalType"];
      /** Format: int64 */
      id?: number;
      name?: string | null;
    };
    /** @description Dog animal */
    Dog: components["schemas"]["Animal"] & {
      dogUniqueProp?: string | null;
    };
    /** @description Cat animal */
    Cat: components["schemas"]["Animal"] & {
      catUniqueProp?: string | null;
    };
  };
}

export interface operations {}

export interface external {}
